use pest_derive::Parser;

// The Parser derive will automatically generate a Rule enum from the grammar
#[derive(Parser)]
#[grammar = "src/parser/parser.pest"]
pub struct TungParser;

// Re-export necessary items from pest for convenience
#[allow(unused_imports)]
pub use pest::Parser;

// The Rule enum is automatically generated by pest_derive
// so we don't need to define it ourselves
